In [1]:
# Array Operations using Python, NumPy and Pandas

import numpy as np
import pandas as pd

# -------------------------------
# 1. One-Dimensional Array
# -------------------------------

arr = [1, 2, 3, 4, 5, 6]

print("One-Dimensional Array:", arr)

# Indexing
print("\nIndexing:")
print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

# Slicing
print("\nSlicing:")
print("Elements from index 1 to 4:", arr[1:5])

# Start, Stop and Step
print("\nStart, Stop and Step:")
print("Start=0, Stop=6, Step=2:", arr[0:6:2])
print("Start=1, Stop=6, Step=2:", arr[1:6:2])

# Reverse Array
print("\nReverse Array:")
print(arr[::-1])


# -------------------------------
# 2. Two-Dimensional Array
# -------------------------------

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\n\nTwo-Dimensional Array:")
print(arr2)

# Indexing
print("\nIndexing:")
print("First element:", arr2[0, 0])
print("Element at row 2, column 3:", arr2[1, 2])

# Slicing
print("\nSlicing:")
print("First two rows:")
print(arr2[0:2, :])

print("First two columns:")
print(arr2[:, 0:2])

# Start, Stop and Step
print("\nStart, Stop and Step:")
print("Every alternate row:")
print(arr2[0:3:2])

print("Every alternate column:")
print(arr2[:, 0:3:2])

# Reverse 2-D Array
print("\nReverse 2-D Array:")
print(arr2[::-1, ::-1])


# -------------------------------
# 3. NumPy Operations
# -------------------------------

print("\n\nNumPy Operations:")

a = np.array([20, 40, 60, 80, 100])
b = np.array([10, 20, 30, 40, 50])

print("Array A:", a)
print("Array B:", b)

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("Sum of A:", np.sum(a))
print("Maximum of A:", np.max(a))
print("Minimum of A:", np.min(a))
print("Mean of A:", np.mean(a))


# -------------------------------
# 4. Pandas Operations
# -------------------------------

print("\n\nPandas Operations:")

data = {
    "Name": ["pavan", "lepu", "chandan", "hemanth"],
    "Marks": [95, 82, 98, 78],
    "Age": [19, 19, 20, 18]
}

df = pd.DataFrame(data)

print("\nDataFrame:")
print(df)

# Selecting a column
print("\nMarks Column:")
print(df["Marks"])

# Selecting rows
print("\nFirst two rows:")
print(df.iloc[0:2])

# Basic operations
print("\nAverage Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

# Sorting
print("\nData sorted by Marks:")
print(df.sort_values("Marks"))

# Filtering
print("\nStudents with marks greater than 80:")
print(df[df["Marks"] > 80])

One-Dimensional Array: [1, 2, 3, 4, 5, 6]

Indexing:
First element: 1
Third element: 3
Last element: 6

Slicing:
Elements from index 1 to 4: [2, 3, 4, 5]

Start, Stop and Step:
Start=0, Stop=6, Step=2: [1, 3, 5]
Start=1, Stop=6, Step=2: [2, 4, 6]

Reverse Array:
[6, 5, 4, 3, 2, 1]


Two-Dimensional Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Indexing:
First element: 1
Element at row 2, column 3: 6

Slicing:
First two rows:
[[1 2 3]
 [4 5 6]]
First two columns:
[[1 2]
 [4 5]
 [7 8]]

Start, Stop and Step:
Every alternate row:
[[1 2 3]
 [7 8 9]]
Every alternate column:
[[1 3]
 [4 6]
 [7 9]]

Reverse 2-D Array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


NumPy Operations:
Array A: [ 20  40  60  80 100]
Array B: [10 20 30 40 50]
Addition: [ 30  60  90 120 150]
Subtraction: [10 20 30 40 50]
Multiplication: [ 200  800 1800 3200 5000]
Division: [2. 2. 2. 2. 2.]
Sum of A: 300
Maximum of A: 100
Minimum of A: 20
Mean of A: 60.0


Pandas Operations:

DataFrame:
      Name  Marks  Age
0    pavan     95   19
1     lepu 